# Configuração do datasource SQLite
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:./data/investimentos.db
quarkus.datasource.username=
quarkus.datasource.password=

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Não usamos mais import.sql, pois o DataLoader cuida dos seeds
# quarkus.hibernate-orm.sql-load-script=import.sql