# Perfil de desenvolvimento (SQLite)
# %dev.quarkus.datasource.db-kind=sqlite
# %dev.quarkus.datasource.jdbc.url=jdbc:sqlite:./data/investimentos.db
# %dev.quarkus.hibernate-orm.database.generation=drop-and-create
# quarkus.datasource.username=
# quarkus.datasource.password=

# Perfil de testes (H2 em memória)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:investimentos;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
#%test.