# Conexão db SQLite
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:./data/investimentos.db
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
